[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ciaranm/securemodelines'
hook_add = '''
  set modelines=0
  set nomodeline
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
  set background=dark
  let g:gruvbox_material_foreground = 'original'
  let g:gruvbox_material_transparent_background = 1
  colorscheme gruvbox-material
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = [
        \   'csv',
        \   'ftdetect',
        \   'go',
        \   'jsx',
        \   'markdown',
        \ ]
'''

[[plugins]]
repo = 'mattn/vim-gomod'

[[plugins]]
repo = 'mattn/vim-molder'
hook_add = '''
  let g:molder_show_hidden = 1
'''

[[plugins]]
repo = 'mattn/vim-molder-operations'

[[plugins]]
repo = 'rbtnn/vim-ambiwidth'
hook_add = '''
  let g:ambiwidth_add_list = [
        \   [0x00B7, 0x00B7, 2],
        \   [0x2018, 0x2019, 2],
        \   [0x201c, 0x201d, 2],
        \   [0x2025, 0x2026, 2],
        \ ]
  let g:ambiwidth_cica_enabled = v:false
'''
