[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ciaranm/securemodelines'
hook_add = '''
  set modelines=0
  set nomodeline
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
  set background=dark
  let g:gruvbox_material_foreground = 'original'
  let g:gruvbox_material_transparent_background = 1
  colorscheme gruvbox-material
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = [
        \   'csv',
        \   'ftdetect',
        \   'go',
        \   'jsx',
        \   'markdown',
        \ ]
'''

[[plugins]]
repo = 'mattn/vim-gomod'

[[plugins]]
repo = 'mattn/vim-molder'
hook_add = '''
  let g:molder_show_hidden = 1
'''

[[plugins]]
repo = 'mattn/vim-molder-operations'

