excludes:
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: ponko2/actions/*
  - policy_name: checkout_persist_credentials_should_be_false
    workflow_file_path: .github/workflows/test.yml
    job_name: changed-files
