---
extends: default
ignore: |
  node_modules/
  pnpm-lock.yaml
rules:
  comments:
    level: error
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start:
    ignore: |
      .github/
      lefthook.yml
      pnpm-workspace.yaml
    level: error
  line-length: disable
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false
  quoted-strings:
    quote-type: double
    required: only-when-needed
    extra-required:
      - ^0[0-9]+$
    extra-allowed:
      - ^[0-9]{2}:[0-9]{2}$
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "yes"
      - "no"
      - "on"
      - "off"
    level: error
