[plugins]
luarocks = "https://github.com/ponko2/mise-luarocks"

[settings]
lockfile = true

[tools]
"npm:@commitlint/cli" = "latest"
checkmake = "latest"
editorconfig-checker = "latest"
hk = "latest"
lua = "5.4"
node = "lts"
oxfmt = "latest"
python = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
uv = "latest"

[tools."github:Kampfkarren/selene"]
version = "latest"
bin = "selene"

[tools."luarocks:luacheck"]
version = "latest"
depends = ["lua"]

[tools.yamllint]
version = "latest"
depends = ["python", "uv"]
