[env]
VIMRUNTIME = { value = "{{ tools.neovim.path }}/share/nvim/runtime", tools = true }

[plugins]
luarocks = "https://github.com/ponko2/mise-luarocks"

[tools]
"aqua:owenlamont/ryl" = "latest"
"npm:@commitlint/cli" = "latest"
actionlint = "latest"
checkmake = "latest"
editorconfig-checker = "latest"
ghalint = "latest"
hk = "latest"
lua-language-server = "latest"
neovim = "latest"
oxfmt = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
zizmor = "latest"

[tools."github:Kampfkarren/selene"]
version = "latest"
bin = "selene"

[tools."luarocks:luacheck"]
version = "latest"
depends = ["lua"]
lazy = true
lazy_bins = ["luacheck"]

[tools.lua]
version = "5.1"
lazy = true
lazy_bins = ["lua", "luac", "luarocks"]
