[env]
VIMRUNTIME = { value = "{{ tools.neovim.path }}/share/nvim/runtime", tools = true }

[plugins]
luarocks = "https://github.com/ponko2/mise-luarocks"

[settings]
lockfile = true

[tools]
"aqua:owenlamont/ryl" = "latest"
"npm:@commitlint/cli" = "latest"
actionlint = "latest"
checkmake = "latest"
editorconfig-checker = "latest"
ghalint = "latest"
hk = "latest"
lua = "5.4"
lua-language-server = "latest"
neovim = "latest"
oxfmt = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
zizmor = "latest"

[tools."github:Kampfkarren/selene"]
version = "latest"
bin = "selene"

[tools."luarocks:luacheck"]
version = "latest"
depends = ["lua"]
