update

upgrade

tap homebrew/dupes
tap homebrew/apache
tap homebrew/binary
tap homebrew/versions
tap caskroom/cask
tap caskroom/versions
tap josegonzalez/php
tap peco/peco
tap sanemat/font

install zsh
install git
install jq
install httpie
install node
install sqlite
install macvim --HEAD --override-system-vim --with-lua --with-luajit
install the_silver_searcher
install the_platinum_searcher
install wget
install watch
install rsync
install unrar
install exiftool
install imagemagick
install dos2unix
install colordiff
install nkf
install httpd22
install putty
install openssh
install ssh-copy-id
install rbenv
install ruby-build
install php54
install php54-intl
install php54-mcrypt
install php54-xdebug
install phpmd
install php-cs-fixer
install php-code-sniffer
install peco
install ricty --vim-powerline

install brew-cask
cask install java6 || true
cask install xquartz || true
cask install dash || true
cask install alfred || true
cask install slate || true
cask install clipmenu || true
cask install onepassword || true
cask install skitch || true
cask install the-unarchiver || true
cask install sourcetree || true
cask install sequel-pro || true
cask install cyberduck || true
cask install dropbox || true
cask install pdftk || true
cask install iterm2 || true
cask install xtrafinder || true
cask install virtualbox || true
cask install vagrant || true
cask install vagrant-manager || true
cask install boot2docker || true
cask install atom || true
cask install vlc || true
cask install fluid || true
cask install firefox || true
cask install google-drive || true
cask install google-hangouts || true
cask install google-chrome-beta || true
cask install google-japanese-ime || true
cask install phpstorm-eap || true
cask install android-file-transfer || true
cask install caffeine || true
cask install appcleaner || true

cleanup
