update

upgrade

tap homebrew/dupes
tap homebrew/binary
tap homebrew/versions
tap phinze/cask
tap caskroom/versions
tap josegonzalez/php
tap sanemat/font

install zsh
install git
install jq
install node
install sqlite
install macvim --override-system-vim --with-luajit
install the_silver_searcher
install wget
install watch
install rsync
install unrar
install exiftool
install imagemagick
install dos2unix
install colordiff
install nkf
install httpd
install putty
install openssh
install ssh-copy-id
install rbenv
install ruby-build
install php54
install php54-intl
install php54-mcrypt
install php54-xdebug
install phpmd
install php-cs-fixer
install php-code-sniffer
install ricty --vim-powerline

install brew-cask
cask install java6
cask install xquartz
cask install dash
cask install alfred
cask install slate
cask install clipmenu
cask install onepassword
cask install skitch
cask install the-unarchiver
cask install sourcetree
cask install cyberduck
cask install dropbox
cask install pdftk
cask install iterm2
cask install xtrafinder
cask install virtualbox
cask install vagrant
cask install vlc
cask install firefox
cask install google-drive
cask install google-hangouts
cask install google-chrome-beta
cask install google-japanese-ime
cask install phpstorm-eap
cask install airmail
cask install appcleaner

cleanup
