[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ciaranm/securemodelines'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = [
        \   'csv',
        \   'ftdetect',
        \   'go',
        \   'jsx',
        \   'markdown',
        \ ]
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'mattn/vim-gomod'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'mhinz/vim-signify'
hook_add = '''
  let g:signify_vcs_cmds = {
        \   'git': 'git diff --no-color --no-ext-diff -U0 HEAD -- %f',
        \ }
'''

[[plugins]]
repo = 'mattn/vim-molder'
hook_add = '''
  let g:molder_show_hidden = 1
'''

[[plugins]]
repo = 'mattn/vim-molder-operations'

[[plugins]]
repo = 'rbtnn/vim-ambiwidth'
hook_add = '''
  let g:ambiwidth_add_list = [
        \   [0x00B7, 0x00B7, 2],
        \   [0x2018, 0x2019, 2],
        \   [0x201c, 0x201d, 2],
        \   [0x2025, 0x2026, 2],
        \ ]
  let g:ambiwidth_cica_enabled = v:false
'''
