[[plugins]]
repo = 'zchee/deoplete-go'
on_i = 1
on_ft = 'go'
build = 'make'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_i = 1
on_ft = 'javascript'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_i = 1
on_ft = 'ruby'

[[plugins]]
repo = 'pbogut/deoplete-padawan'
on_i = 1
on_ft = 'php'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> <Leader>N :<C-u>call deol#new({'command': 'fish'})<CR>
  nnoremap <silent> <Leader>s :<C-u>Deol fish<CR>
'''
