[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'haya14busa/vim-textobj-function-syntax'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'cespare/vim-toml'

# [[plugins]]
# repo = 'billyvg/tigris.nvim'
# build = './install.sh'
# hook_add = '''
#   let g:tigris#enabled = 1
#   let g:tigris#on_the_fly_enabled = 1
#   let g:tigris#delay = 300
# '''

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/es.next.syntax.vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
hook_add = '''
  let g:gfm_syntax_emoji_conceal = 1
  let g:markdown_fenced_languages = ['java', 'javascript', 'json']
'''

[[plugins]]
repo = 'mustache/vim-mustache-handlebars'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_diff_base = 'HEAD'
'''

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'bfredl/nvim-miniyank'
if = "has('nvim')"
on_map = '<Plug>(miniyank-'
hook_add = '''
  nmap p <Plug>(miniyank-autoput)
  nmap P <Plug>(miniyank-autoPut)
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
  " npm install -g javascript-typescript-langserver
  " npm install -g vue-language-server
  let g:LanguageClient_serverCommands = {
        \   'javascript': ['javascript-typescript-stdio'],
        \   'vue': ['vls'],
        \ }

  autocmd MyAutoCmd FileType javascript,vue nnoremap <buffer> <silent> K :call LanguageClient#textDocument_hover()<CR>
  autocmd MyAutoCmd FileType javascript,vue nnoremap <buffer> <silent> gd :call LanguageClient#textDocument_definition()<CR>
  autocmd MyAutoCmd FileType javascript,vue nnoremap <buffer> <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''
