[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'thinca/vim-textobj-between'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'haya14busa/vim-textobj-function-syntax'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = [
        \   'csv',
        \   'go',
        \   'jsx',
        \   'markdown',
        \ ]
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_diff_base = 'HEAD'
'''

[[plugins]]
repo = 'bfredl/nvim-miniyank'
if = "has('nvim')"
on_map = '<Plug>(miniyank-'
hook_add = '''
  nmap p <Plug>(miniyank-autoput)
  nmap P <Plug>(miniyank-autoPut)
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
  let g:LanguageClient_fzfContextMenu = 0
  let g:LanguageClient_diagnosticsEnable = 0
  let g:LanguageClient_serverCommands = {
        \   'javascript': ['typescript-language-server', '--stdio'],
        \   'css': ['css-languageserver', '--stdio'],
        \   'scss': ['css-languageserver', '--stdio'],
        \   'less': ['css-languageserver', '--stdio'],
        \   'html': ['html-languageserver', '--stdio'],
        \   'vue': ['vls'],
        \ }

  function! s:LC_maps()
    if has_key(g:LanguageClient_serverCommands, &filetype)
      nnoremap <buffer> <silent> K :call LanguageClient#textDocument_hover()<CR>
      nnoremap <buffer> <silent> gd :call LanguageClient#textDocument_definition()<CR>
      nnoremap <buffer> <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
      nnoremap <buffer> <silent> <F5> :call LanguageClient_contextMenu()<CR>
    endif
  endfunction

  autocmd MyAutoCmd FileType * call s:LC_maps()
'''
