[[plugins]]
repo = 'jodosha/vim-godebug'
on_ft = 'go'

[[plugins]]
repo = 'bfredl/nvim-miniyank'
on_map = '<Plug>(miniyank-'
hook_add = '''
  nmap p <Plug>(miniyank-autoput)
  nmap P <Plug>(miniyank-autoPut)
'''
