[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  if IsWindows()
    " 斜体表示をしない
    let g:gruvbox_italic = 0
  endif

  set background=dark
  autocmd MyAutoCmd VimEnter * nested colorscheme gruvbox
'''
