[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> <Leader>j :<C-u>Denite junkfile:new junkfile
        \ -default-action=split<CR>
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_ft = 'snippet'
on_event = 'InsertEnter'
hook_source = 'call vimrc#source_rc("plugins/neosnippet.rc.vim")'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'call vimrc#source_rc("plugins/denite.rc.vim")'
hook_add = '''
  nnoremap <silent> <C-p> :<C-u>Denite -sorters=sorter/sublime file/point file/old
        \ `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`
        \ file file:new<CR>

  nnoremap <silent> <Leader>. :<C-u>DeniteBufferDir -sorters=sorter/sublime
        \ `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`<CR>

  nnoremap <silent> <Leader><Tab> :<C-u>Denite buffer<CR>

  nnoremap <silent> <Leader>/ :<C-u>Denite -buffer-name=search -no-empty -mode=normal grep::!<CR>
  nnoremap <silent> <Leader>n :<C-u>Denite -buffer-name=search -resume -mode=normal -refresh<CR>
  nnoremap <silent> <Leader>p :<C-u>Denite -buffer-name=register register neoyank<CR>
  xnoremap <silent> <Leader>p :<C-u>Denite -buffer-name=register -default-action=replace register neoyank<CR>
  nnoremap <silent> <Leader>; :<C-u>Denite -unique -mode=normal change jump<CR>
'''

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> <Leader><C-p> :<C-u>Denite -default-action=cd ghq<CR>
'''

[[plugins]]
repo = 'chemzqm/denite-git'
depends = 'vim-easygit'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> <Leader>gs :<C-u>Denite gitstatus<CR>
'''

[[plugins]]
repo = 'chemzqm/vim-easygit'

[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_source = 'call vimrc#source_rc("plugins/defx.rc.vim")'
hook_add = '''
nnoremap <silent> <Leader>f :<C-u>Defx `expand('%:p:h')`
        \ -split=vertical -winwidth=50 -direction=topleft
        \ -search=`expand('%:p')`<CR>
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
depends = 'denite.nvim'
hook_add = '''
  nnoremap <silent> <Leader>s :<C-u>Deol -split zsh<CR>
  nnoremap <silent> <Leader>S :<C-u>Deol zsh<CR>
  " nnoremap <silent> <Leader>S :<C-u>call deol#new({'command': 'zsh'})<CR>
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = {xn = '<Plug>(EasyAlign)'}
hook_add = '''
  " Start interactive EasyAlign in visual mode (e.g. vipga)
  xmap ga <Plug>(EasyAlign)

  " Start interactive EasyAlign for a motion/text object (e.g. gaip)
  nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
hook_add = '''
  nnoremap <silent> <Leader>gS :<C-u>Gina status<CR>
  nnoremap <silent> <Leader>gc :<C-u>Gina commit<CR>
'''

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap I <Plug>(niceblock-I)
  xmap A <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap p <Plug>(operator-replace)
'''

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = {nv = '<Plug>'}
hook_add = '''
  nmap J <Plug>(jplus)
  vmap J <Plug>(jplus)
  nmap <Leader>J <Plug>(jplus-input)
  vmap <Leader>J <Plug>(jplus-input)
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-surround-'
hook_add = '''
  map <silent>sa <Plug>(operator-surround-append)
  map <silent>sd <Plug>(operator-surround-delete)
  map <silent>sr <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'thinca/vim-visualstar'
on_map = {v = '<Plug>(visualstar-'}
hook_add = '''
  vmap *  <Plug>(visualstar-*)zv
  vmap #  <Plug>(visualstar-#)zv
  vmap g* <Plug>(visualstar-g*)zv
  vmap g# <Plug>(visualstar-g#)zv
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_event = 'InsertEnter'
hook_source = '''
  let g:user_emmet_settings = {
        \   'variables': {
        \     'lang': 'ja',
        \   },
        \ }
'''

# npm install -g import-js
[[plugins]]
repo = 'Galooshi/vim-import-js'
on_ft = 'javascript'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_types = 1
  let g:go_highlight_build_constraints = 1
  let g:go_highlight_generate_tags = 1

  let g:go_auto_sameids = 1
  let g:go_auto_type_info = 0

  let g:go_fmt_command = 'gofmt'
  let g:go_fmt_fail_silently = 1
  let g:go_fmt_options = {
        \   'gofmt': '-s',
        \   'goimports': '',
        \ }

  let g:go_snippet_engine = "neosnippet"

  let g:go_gocode_unimported_packages = 1

  let g:go_metalinter_enabled = [
        \   'deadcode',
        \   'dupl',
        \   'errcheck',
        \   'gas',
        \   'goconst',
        \   'gocyclo',
        \   'golint',
        \   'gosimple',
        \   'gotype',
        \   'gotypex',
        \   'ineffassign',
        \   'interfacer',
        \   'maligned',
        \   'megacheck',
        \   'staticcheck',
        \   'structcheck',
        \   'unconvert',
        \   'varcheck',
        \   'vet',
        \   'vetshadow',
        \ ]
'''
hook_add = '''
  " run :GoBuild or :GoTestCompile based on the go file
  function! s:build_go_files()
    let l:file = expand('%')
    if l:file =~# '^\f\+_test\.go$'
      call go#test#Test(0, 1)
    elseif l:file =~# '^\f\+\.go$'
      call go#cmd#Build(0)
    endif
  endfunction

  augroup Golang
    autocmd!

    autocmd FileType go nmap <buffer> K <Plug>(go-info)
    autocmd FileType go nmap <buffer> <F2> <Plug>(go-rename)
    autocmd FileType go nmap <buffer> <C-g> :<C-u>Denite decls<CR>
    autocmd FileType go imap <buffer> <C-g> <ESC>:<C-u>Denite decls<CR>

    autocmd FileType go nmap <buffer> <Leader>i <Plug>(go-imports)

    autocmd FileType go nmap <buffer> <Leader>A <Plug>(go-alternate-edit)
    autocmd FileType go nmap <buffer> <Leader>B :<C-u>call <SID>build_go_files()<CR>
    autocmd FileType go nmap <buffer> <Leader>C <Plug>(go-coverage-toggle)
    autocmd FileType go nmap <buffer> <Leader>I <Plug>(go-install)
    autocmd FileType go nmap <buffer> <Leader>L <Plug>(go-metalinter)
    autocmd FileType go nmap <buffer> <Leader>R <Plug>(go-run)
    autocmd FileType go nmap <buffer> <Leader>S <Plug>(go-def-split)
    autocmd FileType go nmap <buffer> <Leader>T <Plug>(go-test)
    autocmd FileType go nmap <buffer> <Leader>V <Plug>(go-def-vertical)

    autocmd Filetype go command! -buffer -bang A call go#alternate#Switch(<bang>0, 'edit')
    autocmd Filetype go command! -buffer -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
    autocmd Filetype go command! -buffer -bang AS call go#alternate#Switch(<bang>0, 'split')
    autocmd Filetype go command! -buffer -bang AT call go#alternate#Switch(<bang>0, 'tabe')
  augroup END
'''

[[plugins]]
repo = 'w0rp/ale'
on_if = 1
hook_source = '''
  let g:ale_sign_column_always = 1
  let g:ale_sign_error = '✖'
  let g:ale_sign_warning = '⚠'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

  let g:ale_linters = {
        \   'go': ['golangci-lint'],
        \   'html': [],
        \   'java': [],
        \   'javascript': ['eslint'],
        \   'markdown': ['textlint'],
        \   'text': ['textlint'],
        \   'zsh': [],
        \ }

  let g:ale_fix_on_save = 1
  let g:ale_fixers = {
        \   'javascript': ['eslint'],
        \   'vue': ['eslint'],
        \   'css': ['prettier'],
        \   'scss': ['prettier'],
        \   'less': ['prettier'],
        \ }

  let g:ale_go_golangci_lint_options = ''
  let g:ale_go_golangci_lint_package = 1
'''

[[plugins]]
repo = 'iyuuya/denite-ale'
depends = 'ale'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> <Leader>l :<C-u>Denite -no-empty ale<CR>
'''

[[plugins]]
repo = 'ciaranm/securemodelines'
on_event = 'BufRead'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'
hook_source = '''
  let g:deoplete#sources#go#source_importer = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = 'call vimrc#source_rc("plugins/deoplete.rc.vim")'
