[[plugins]]
repo = 'LeafCage/foldCC'
on_ft = 'vim'
hook_add = '''
  let g:foldCCtext_enable_autofdc_adjuster = 1
  set foldtext=FoldCCtext()
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_i = 1
hook_source = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/neocomplete.rc.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_source = 'denite.nvim'
hook_source = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/unite.rc.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/denite.rc.vim'
hook_add = '''
  nnoremap <silent> <C-p> :<C-u>Denite file_point file_old
        \ `executable('git') && finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'`<CR>

  nnoremap <silent> <Leader>/ :<C-u>Denite -buffer-name=search -no-empty -mode=normal grep<CR>
  nnoremap <silent> <Leader>n :<C-u>Denite -buffer-name=search -resume -mode=normal<CR>

  nnoremap <silent> <Leader>R :<C-u>Denite -buffer-name=register register neoyank<CR>
  xnoremap <silent> <Leader>R :<C-u>Denite -buffer-name=register -default-action=replace register neoyank<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
hook_source = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/vimfiler.rc.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = {xn = '<Plug>(EasyAlign)'}
hook_add = '''
  " Start interactive EasyAlign in visual mode (e.g. vipga)
  xmap ga <Plug>(EasyAlign)

  " Start interactive EasyAlign for a motion/text object (e.g. gaip)
  nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'lambdalisue/vim-gita'
on_cmd = 'Gita'
hook_add = '''
  nnoremap <silent> <Leader>gs :<C-u>Gita status<CR>

  autocmd MyAutoCmd FileType gita-status nmap <buffer> cc <Plug>(gita-commit-open)
  autocmd MyAutoCmd FileType gita-status nmap <buffer> ca <Plug>(gita-commit-open-amend)
'''

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap I <Plug>(niceblock-I)
  xmap A <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap p <Plug>(operator-replace)
'''

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = {nv = '<Plug>'}
hook_add = '''
  nmap J <Plug>(jplus)
  vmap J <Plug>(jplus)
  nmap <Leader>J <Plug>(jplus-input)
  vmap <Leader>J <Plug>(jplus-input)
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-surround-'
hook_add = '''
  map <silent>sa <Plug>(operator-surround-append)
  map <silent>sd <Plug>(operator-surround-delete)
  map <silent>sr <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'thinca/vim-visualstar'
on_map = '<Plug>(visualstar-'
hook_add = '''
  map *  <Plug>(visualstar-*)zvzz
  map #  <Plug>(visualstar-#)zvzz
  map g* <Plug>(visualstar-g*)zvzz
  map g# <Plug>(visualstar-g#)zvzz
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php', 'css', 'scss']
hook_add = '''
  let g:user_emmet_install_global = 0
  let g:user_emmet_settings = {
        \   'jsp' : {
        \     'extends' : 'html',
        \     'filters' : 'c',
        \   },
        \   'php' : {
        \     'extends' : 'html',
        \     'filters' : 'c',
        \   },
        \ }
  autocmd MyAutoCmd FileType html,xhtml,jsp,asp,php,css,scss EmmetInstall
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_if = "executable('git') && finddir('.git', ';') != ''"
hook_add = '''
  let g:gitgutter_diff_args = 'HEAD'
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_types = 1
  let g:go_highlight_build_constraints = 1

  let g:go_auto_type_info = 1
  let g:go_fmt_command = 'gofmt'
  let g:go_fmt_options = '-s'
  let g:go_metalinter_autosave = 1

  let g:go_metalinter_enabled = [
        \   'aligncheck',
        \   'deadcode',
        \   'dupl',
        \   'errcheck',
        \   'gas',
        \   'goconst',
        \   'gocyclo',
        \   'golint',
        \   'gosimple',
        \   'gotype',
        \   'ineffassign',
        \   'interfacer',
        \   'staticcheck',
        \   'structcheck',
        \   'unconvert',
        \   'varcheck',
        \   'vet',
        \   'vetshadow',
        \ ]

  let g:go_metalinter_autosave_enabled = [
        \   'deadcode',
        \   'dupl',
        \   'gas',
        \   'goconst',
        \   'gocyclo',
        \   'golint',
        \   'gosimple',
        \   'gotype',
        \   'ineffassign',
        \   'staticcheck',
        \   'vet',
        \   'vetshadow',
        \ ]

  autocmd MyAutoCmd FileType go nmap <Leader>b <Plug>(go-build)
  autocmd MyAutoCmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
  autocmd MyAutoCmd FileType go nmap <Leader>d <Plug>(go-doc)
  autocmd MyAutoCmd FileType go nmap <Leader>e <Plug>(go-rename)
  autocmd MyAutoCmd FileType go nmap <Leader>i <Plug>(go-implements)
  autocmd MyAutoCmd FileType go nmap <Leader>r <Plug>(go-run)
  autocmd MyAutoCmd FileType go nmap <Leader>t <Plug>(go-test)
'''

[[plugins]]
repo = 'neomake/neomake'
on_if = 1

[[plugins]]
repo = 'w0rp/ale'
on_if = 1
hook_add = '''
  let g:ale_sign_column_always = 1
  let g:ale_sign_error = '✖'
  let g:ale_sign_warning = '⚠'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

  let g:ale_linters = {
        \   'html': [],
        \   'javascript': ['eslint'],
        \ }
'''

[[plugins]]
repo = 'ciaranm/securemodelines'
on_event = 'BufRead'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_event = 'BufRead'
