name: setup-nix
description: Set up a Nix environment
inputs:
  cachix-auth-token:
    description: Authentication token for Cachix
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
    - name: Set up Cachix
      uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: ponko2
        authToken: ${{ inputs.cachix-auth-token }}
