# vi: set ft=ruby :

## Command
brew "bat"
brew "colordiff"
brew "curl"
brew "dos2unix"
brew "exiftool"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "git-lfs"
brew "go"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "lsd"
brew "nkf"
brew "openssh"
brew "p7zip"
brew "ripgrep"
brew "ripgrep-all"
brew "rsync"
brew "sheldon"
brew "sqlite"
brew "ssh-copy-id"
brew "starship"
brew "wget"
brew "zoxide"

## Formatter
brew "nixfmt"
brew "shfmt"
brew "stylua"

## Linter
brew "checkmake"
brew "editorconfig-checker"
brew "golangci-lint"
brew "luacheck"
brew "shellcheck"
brew "yamllint"

## Neovim
brew "basedpyright"
brew "lua-language-server"
brew "luarocks"
brew "neovim"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "typescript-language-server"
brew "vue-language-server"

if OS.mac?
  ## GUI Applications
  cask "1password"
  cask "1password-cli"
  cask "adobe-acrobat-reader"
  cask "appcleaner"
  cask "devtoys"
  cask "docker-desktop"
  cask "ghostty"
  cask "iterm2"
  cask "karabiner-elements"
  cask "monitorcontrol"
  cask "rectangle"
  cask "the-unarchiver"
  cask "visual-studio-code"

  ## Fonts
  cask "font-udev-gothic"
  cask "font-udev-gothic-nf"
end
