# vi: set ft=ruby :

## Command
brew "bat"
brew "colordiff"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "git-lfs"
brew "go"
brew "httpie"
brew "jq"
brew "lsd"
brew "ripgrep"
brew "ripgrep-all"
brew "sheldon"
brew "sqlite"
brew "starship"
brew "tree-sitter"
brew "zoxide"

## Format
brew "shfmt"
brew "stylua"

## Lint
brew "checkmake"
brew "editorconfig-checker"
brew "golangci-lint"
brew "luacheck"
brew "shellcheck"
brew "yamllint"

## LSP
brew "basedpyright"
brew "lua-language-server"
brew "typescript-language-server"
brew "vue-language-server"

## Neovim
brew "luarocks"
brew "neovim"

if OS.mac?
  ## Command
  brew "coreutils"
  brew "curl"
  brew "diffutils"
  brew "dos2unix"
  brew "ed"
  brew "exiftool"
  brew "findutils"
  brew "gawk"
  brew "gnu-sed"
  brew "gnu-tar"
  brew "grep"
  brew "gzip"
  brew "imagemagick"
  brew "iproute2mac"
  brew "mysql-client"
  brew "nkf"
  brew "openssh"
  brew "p7zip"
  brew "rsync"
  brew "ssh-copy-id"
  brew "watch"
  brew "wget"

  ## Mac Apps
  #cask "1password"
  #cask "1password-cli"
  #cask "adobe-acrobat-reader"
  #cask "appcleaner"
  cask "devtoys"
  #cask "docker"
  cask "ghostty"
  cask "iterm2"
  cask "karabiner-elements"
  cask "monitorcontrol"
  cask "mysqlworkbench"
  cask "rectangle"
  #cask "the-unarchiver"
  cask "visual-studio-code"

  ## Fonts
  cask "font-udev-gothic"
  cask "font-udev-gothic-nf"

  # App Store
  #brew "mas"
  #mas "Monosnap", id: 540348655
end
