name: Luacheck
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Luacheck
        uses: lunarmodules/luacheck@v1
