name: StyLua
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --allow-hidden --check .
