name: Test
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}
permissions: {}
jobs:
  required:
    name: "Required Checks: Test"
    if: ${{ always() }}
    needs:
      - actionlint
      - biome
      - changed-files
      - editorconfig
      - ghalint
      - luacheck
      - stylua
      - yamllint
      - zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Determine status
        id: status
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            result="failed"
          else
            result="success"
          fi
          {
            echo "result=${result}"
            echo "results=${results}"
          } | tee -a "$GITHUB_OUTPUT"
      - name: Check for failed status
        if: ${{ always() && steps.status.outputs.result != 'success' }}
        run: |
          echo "One or more required build workflows failed: ${{ steps.status.outputs.results }}"
          exit 1
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      # reference: https://github.com/tj-actions/changed-files#outputs-
      biome: ${{ steps.changed-files.outputs.biome_any_modified == 'true' }}
      luacheck: ${{ steps.changed-files.outputs.luacheck_any_modified == 'true' }}
      stylua: ${{ steps.changed-files.outputs.stylua_any_modified == 'true' }}
      workflows: ${{ steps.changed-files.outputs.workflows_any_modified == 'true' }}
      yamllint: ${{ steps.changed-files.outputs.yamllint_any_modified == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          persist-credentials: false
      - name: Get relevant files changed per group
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files_yaml: |
            common: &common
              - .github/workflows/test.yml
            biome:
              - *common
              - "**.{cjs,cts,js,json,jsonc,jsx,mjs,mts,ts,tsx}"
              - biome.json
            luacheck:
              - *common
              - "**.lua"
              - .luacheckrc
              - .luarc.json
            stylua:
              - *common
              - "**.lua"
              - .luarc.json
              - .stylua.toml
            workflows:
              - ".github/workflows/*.{yaml,yml}"
            yamllint:
              - *common
              - "**.{yaml,yml}"
  actionlint:
    name: actionlint
    if: ${{ needs.changed-files.outputs.workflows == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
        with:
          fail_level: warning
          filter_mode: nofilter
          reporter: github-pr-annotations
  biome:
    name: Biome
    if: ${{ needs.changed-files.outputs.biome == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup Biome
        uses: biomejs/setup-biome@f382a98e582959e6aaac8e5f8b17b31749018780 # v2.5.0
      - name: Run Biome
        run: biome ci
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: editorconfig-checker/action-editorconfig-checker@d2ed4fd072ae6f887e9407c909af0f585d2ad9f4 # v2
      - run: editorconfig-checker
  ghalint:
    name: ghalint
    if: ${{ needs.changed-files.outputs.workflows == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up ghalint
        env:
          GHALINT_VERSION: v1.3.0
          GH_TOKEN: ${{ github.token }}
        run: |
          TMPDIR=$(mktemp -d)
          gh release download "$GHALINT_VERSION" -R suzuki-shunsuke/ghalint -p "ghalint_*_linux_amd64.tar.gz" -O "$TMPDIR/ghalint.tar.gz"
          gh attestation verify "$TMPDIR/ghalint.tar.gz" -R suzuki-shunsuke/ghalint --signer-workflow suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml
          tar -C /usr/local/bin -xzf "$TMPDIR/ghalint.tar.gz"
      - name: Run ghalint
        run: ghalint run
  luacheck:
    name: Luacheck
    if: ${{ needs.changed-files.outputs.luacheck == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run Luacheck
        uses: lunarmodules/luacheck@cc089e3f65acdd1ef8716cc73a3eca24a6b845e4 # v1.2.0
  stylua:
    name: StyLua
    if: ${{ needs.changed-files.outputs.stylua == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run StyLua
        uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --allow-hidden --check .
  yamllint:
    name: yamllint
    if: ${{ needs.changed-files.outputs.yamllint == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1.21.0
        with:
          fail_level: error
          filter_mode: nofilter
          reporter: github-pr-annotations
  zizmor:
    name: zizmor
    if: ${{ needs.changed-files.outputs.workflows == 'true' }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
        with:
          enable-cache: false
      - name: Run zizmor
        env:
          GH_TOKEN: ${{ github.token }}
        run: uvx zizmor@1.6.0 -p --format=github --min-severity=low .github/workflows
